# Generated by Django 3.2.15 on 2022-10-03 05:53

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', django_resized.forms.ResizedImageField(crop=['top', 'left', 'right'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 220], upload_to='projects')),
                ('url', models.CharField(max_length=255)),
                ('github_url', models.CharField(max_length=255)),
            ],
        ),
    ]
